# Generated by Django 5.1.7 on 2025-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=24)),
                ('last', models.CharField(max_length=24)),
                ('age', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
