runtime: python312

entrypoint: gunicorn cs348_project.wsgi

instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: cs348_project.settings

handlers:
- url: /static
  static_dir: staticfiles

- url: /.*
  script: auto
